### ISSUE TITLE
アイテム大量取得による負荷を軽減する

### ISSUE THREAD

**Issue by Siroshun09** [okocraft/Box#13]
鯖内での検証の通り、
拾う → DBから元の値取得 → 元の値 + 拾った数 → DBに新しい値をセット → 書き込み → 拾う
というのを **1つ拾うごとに行っている** ので拾い切るのに時間がかかる上に鯖が一瞬止まる。
負荷的観点や、鯖民でもアイテム大量に拾えば鯖を容易に落とすことも可能ではあるので、修正は必須と思われる。

**Comment by LazyGon** [comment]
いずれオンラインプレイヤーのアイテムデータを守りに保存してログアウトとともに記録するようにしたいと思ってます
そうすればかなり変わるはず

いずれってのは、結構な転換が必要だからなんですけどまぁ頑張るしかない

**Comment by LazyGon** [comment]
更新により問題消滅
