### ISSUE TITLE
DB に記録されていないプレイヤーがログインした時の負荷軽減

### ISSUE THREAD

**Issue by Siroshun09** [okocraft/Box#14]
DB に記録されていない = お初さん がログインした際、おそらく初期値をセットするのに非常に負荷がかかっている。鯖が数秒間止まる現象も確認されている。
これもこれで大きな問題なので修正が必要です。

**Comment by akaregi** [comment]
多分メインスレッドでやってるから止まるんだと思うので、非同期にやればよさそう。

**Comment by LazyGon** [comment]
そもそも全アイテム分、一アイテム一アクセスで初期設定書きこみしてるのが原因で、現在のソースでは一気に初期設定書くようにしたからすでに改善されてるはず

むろんそこも非同期にすればより軽いと思われ

**Comment by LazyGon** [comment]
なお、メインでは古いソースで稼働している

**Comment by LazyGon** [comment]
更新により問題消滅
