### ISSUE TITLE
メモリリークを起こす問題

### ISSUE THREAD

**Issue by akaregi** [okocraft/Box#3]
とりあえず issue を起こす。

----

### 原因？

* 多分 `Statement` / `ResultSet` を close していない。こいつらを close しないで放置しておくとメモリリークの原因になるという。

> https://www.atmarkit.co.jp/bbs/phpBB/viewtopic.php?topic=43209&forum=12

### 解決？

* `Statement#close`, `ResultSet#close` を叩く。

> https://teratail.com/questions/1553
> https://qiita.com/opengl-8080/items/a08b0f231f55a44c0151

**Comment by akaregi** [comment]
@LazyGon

**Comment by LazyGon** [comment]
なるほど

**Comment by LazyGon** [comment]
クローズしたらメモリリークしなくなりました
