### ISSUE TITLE
Event#setCancelled() と Event#getItem()#remove() が二回呼ばれている

### ISSUE THREAD

**Issue by akaregi** [okocraft/Box#7]
https://github.com/okocraft/Box/blob/75f4eb86ae877a0df79b9f406e244abcbee57bdf/src/main/java/net/okocraft/box/listeners/EntityPickupItem.java#L48-L49

と

https://github.com/okocraft/Box/blob/75f4eb86ae877a0df79b9f406e244abcbee57bdf/src/main/java/net/okocraft/box/listeners/EntityPickupItem.java#L59-L60

が同じコードで重複してるふうに思えるんですけど意図してる？

**Comment by akaregi** [comment]
してるなら #5 で直します

**Comment by LazyGon** [comment]
上の方のやつは消し忘れです

**Comment by akaregi** [comment]
OK

**Comment by akaregi** [comment]
0a28c96a4860153dc39923017f08a0edfaf917a2 で解決
